### ISSUE TITLE
cannot access benchmark data

### ISSUE THREAD

**Issue by DietDietDiet** [Leezekun/MMSci#1]
hi， thanks for the great work! is the link to the benchmark broken?

**Comment by Leezekun** [comment]
Hi, thank you for your interest. 

Can you try using different browsers other than Chrome?

**Comment by gabrielilharco** [comment]
Same here, I get `ERROR 403: Forbidden` with `wget https://mmsci.s3.amazonaws.com/benchmark.zip`. The raw data and pretraining data both download fine.

**Comment by Leezekun** [comment]
Thanks for the interest in our work. 

The benchmark.zip file should now be available for download.

**Comment by Leezekun** [comment]
solved
